### ISSUE TITLE
TODO!! 

### ISSUE THREAD

**Issue by pranavtbhat** [pranavtbhat/kiwi#1]
This list will keep growing!

# Data Structures
- [ ] Linked List (Adhering to List interface)
- [ ] Array List (Adhering to List interface)
- [ ] Hash Map (Adhering to Map interface)
- [ ] Tree Map (Adhering to Map interface)
- [ ] Generic Undirected Graph
- [ ] Generic Directed Graph
- [ ] Priority Queues
- [ ] Disjoint Set
- [ ] B-Tree

# Algorithms

## ArrayUtils
- [x] String representations
- [x] Primitive to Object boosting
- [x] Bounds Checking
- [x] Swap 
- [ ] Copy

## MathUtils
- [x] Max
- [x] Min
- [x] Mean
- [ ] Median
- [ ] Mode 

## Array Sorting
- [x] Selection Sort
- [x] Bubble Sort
- [x] Insertion Sort
- [x] Merge Sort
- [ ] Count Sort
- [ ] Quick Sort
- [ ] Radix Sort
- [ ] Parallelized Sorts

## Searching
- [ ] Binary Search
- [ ] Quick Select, Majority element

## String Stuff
- [ ] Regex Pattern matching
- [ ] 

## Dynamic Programming
- [ ] Coins Change Problem

# Web Server !!!
- [ ] Java Sockets
- [ ] Directory listing
- [ ] Servlets etc
